//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieServiceUser.MovieServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Movie", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Movie : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirectorField;
        
        private int YearField;
        
        private double RatingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Director {
            get {
                return this.DirectorField;
            }
            set {
                if ((object.ReferenceEquals(this.DirectorField, value) != true)) {
                    this.DirectorField = value;
                    this.RaisePropertyChanged("Director");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((this.RatingField.Equals(value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRating", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UserRating : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MovieTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        private float RatingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MovieTitle {
            get {
                return this.MovieTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.MovieTitleField, value) != true)) {
                    this.MovieTitleField = value;
                    this.RaisePropertyChanged("MovieTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public float Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((this.RatingField.Equals(value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MovieServiceReference.MovieServiceSoap")]
    public interface MovieServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        MovieServiceUser.MovieServiceReference.HelloWorldResponse HelloWorld(MovieServiceUser.MovieServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<MovieServiceUser.MovieServiceReference.HelloWorldResponse> HelloWorldAsync(MovieServiceUser.MovieServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetMoviesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMovies", ReplyAction="*")]
        MovieServiceUser.MovieServiceReference.GetMoviesResponse GetMovies(MovieServiceUser.MovieServiceReference.GetMoviesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMovies", ReplyAction="*")]
        System.Threading.Tasks.Task<MovieServiceUser.MovieServiceReference.GetMoviesResponse> GetMoviesAsync(MovieServiceUser.MovieServiceReference.GetMoviesRequest request);
        
        // CODEGEN: Generating message contract since element name Title from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddMovie", ReplyAction="*")]
        MovieServiceUser.MovieServiceReference.AddMovieResponse AddMovie(MovieServiceUser.MovieServiceReference.AddMovieRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddMovie", ReplyAction="*")]
        System.Threading.Tasks.Task<MovieServiceUser.MovieServiceReference.AddMovieResponse> AddMovieAsync(MovieServiceUser.MovieServiceReference.AddMovieRequest request);
        
        // CODEGEN: Generating message contract since element name title from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchMovies", ReplyAction="*")]
        MovieServiceUser.MovieServiceReference.SearchMoviesResponse SearchMovies(MovieServiceUser.MovieServiceReference.SearchMoviesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchMovies", ReplyAction="*")]
        System.Threading.Tasks.Task<MovieServiceUser.MovieServiceReference.SearchMoviesResponse> SearchMoviesAsync(MovieServiceUser.MovieServiceReference.SearchMoviesRequest request);
        
        // CODEGEN: Generating message contract since element name movieTitle from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddRating", ReplyAction="*")]
        MovieServiceUser.MovieServiceReference.AddRatingResponse AddRating(MovieServiceUser.MovieServiceReference.AddRatingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddRating", ReplyAction="*")]
        System.Threading.Tasks.Task<MovieServiceUser.MovieServiceReference.AddRatingResponse> AddRatingAsync(MovieServiceUser.MovieServiceReference.AddRatingRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        MovieServiceUser.MovieServiceReference.LoginResponse Login(MovieServiceUser.MovieServiceReference.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<MovieServiceUser.MovieServiceReference.LoginResponse> LoginAsync(MovieServiceUser.MovieServiceReference.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddUser", ReplyAction="*")]
        MovieServiceUser.MovieServiceReference.AddUserResponse AddUser(MovieServiceUser.MovieServiceReference.AddUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddUser", ReplyAction="*")]
        System.Threading.Tasks.Task<MovieServiceUser.MovieServiceReference.AddUserResponse> AddUserAsync(MovieServiceUser.MovieServiceReference.AddUserRequest request);
        
        // CODEGEN: Generating message contract since element name movieTitle from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMovieAverageRating", ReplyAction="*")]
        MovieServiceUser.MovieServiceReference.GetMovieAverageRatingResponse GetMovieAverageRating(MovieServiceUser.MovieServiceReference.GetMovieAverageRatingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMovieAverageRating", ReplyAction="*")]
        System.Threading.Tasks.Task<MovieServiceUser.MovieServiceReference.GetMovieAverageRatingResponse> GetMovieAverageRatingAsync(MovieServiceUser.MovieServiceReference.GetMovieAverageRatingRequest request);
        
        // CODEGEN: Generating message contract since element name movieTitle from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetMovieAverageRating", ReplyAction="*")]
        MovieServiceUser.MovieServiceReference.SetMovieAverageRatingResponse SetMovieAverageRating(MovieServiceUser.MovieServiceReference.SetMovieAverageRatingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetMovieAverageRating", ReplyAction="*")]
        System.Threading.Tasks.Task<MovieServiceUser.MovieServiceReference.SetMovieAverageRatingResponse> SetMovieAverageRatingAsync(MovieServiceUser.MovieServiceReference.SetMovieAverageRatingRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserRatings", ReplyAction="*")]
        MovieServiceUser.MovieServiceReference.GetUserRatingsResponse GetUserRatings(MovieServiceUser.MovieServiceReference.GetUserRatingsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserRatings", ReplyAction="*")]
        System.Threading.Tasks.Task<MovieServiceUser.MovieServiceReference.GetUserRatingsResponse> GetUserRatingsAsync(MovieServiceUser.MovieServiceReference.GetUserRatingsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public MovieServiceUser.MovieServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(MovieServiceUser.MovieServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public MovieServiceUser.MovieServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(MovieServiceUser.MovieServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMoviesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMovies", Namespace="http://tempuri.org/", Order=0)]
        public MovieServiceUser.MovieServiceReference.GetMoviesRequestBody Body;
        
        public GetMoviesRequest() {
        }
        
        public GetMoviesRequest(MovieServiceUser.MovieServiceReference.GetMoviesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetMoviesRequestBody {
        
        public GetMoviesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMoviesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMoviesResponse", Namespace="http://tempuri.org/", Order=0)]
        public MovieServiceUser.MovieServiceReference.GetMoviesResponseBody Body;
        
        public GetMoviesResponse() {
        }
        
        public GetMoviesResponse(MovieServiceUser.MovieServiceReference.GetMoviesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMoviesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MovieServiceUser.MovieServiceReference.Movie[] GetMoviesResult;
        
        public GetMoviesResponseBody() {
        }
        
        public GetMoviesResponseBody(MovieServiceUser.MovieServiceReference.Movie[] GetMoviesResult) {
            this.GetMoviesResult = GetMoviesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMovieRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMovie", Namespace="http://tempuri.org/", Order=0)]
        public MovieServiceUser.MovieServiceReference.AddMovieRequestBody Body;
        
        public AddMovieRequest() {
        }
        
        public AddMovieRequest(MovieServiceUser.MovieServiceReference.AddMovieRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddMovieRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Director;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Year;
        
        public AddMovieRequestBody() {
        }
        
        public AddMovieRequestBody(string Title, string Director, int Year) {
            this.Title = Title;
            this.Director = Director;
            this.Year = Year;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMovieResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMovieResponse", Namespace="http://tempuri.org/", Order=0)]
        public MovieServiceUser.MovieServiceReference.AddMovieResponseBody Body;
        
        public AddMovieResponse() {
        }
        
        public AddMovieResponse(MovieServiceUser.MovieServiceReference.AddMovieResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddMovieResponseBody {
        
        public AddMovieResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchMoviesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchMovies", Namespace="http://tempuri.org/", Order=0)]
        public MovieServiceUser.MovieServiceReference.SearchMoviesRequestBody Body;
        
        public SearchMoviesRequest() {
        }
        
        public SearchMoviesRequest(MovieServiceUser.MovieServiceReference.SearchMoviesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchMoviesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string title;
        
        public SearchMoviesRequestBody() {
        }
        
        public SearchMoviesRequestBody(string title) {
            this.title = title;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchMoviesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchMoviesResponse", Namespace="http://tempuri.org/", Order=0)]
        public MovieServiceUser.MovieServiceReference.SearchMoviesResponseBody Body;
        
        public SearchMoviesResponse() {
        }
        
        public SearchMoviesResponse(MovieServiceUser.MovieServiceReference.SearchMoviesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchMoviesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MovieServiceUser.MovieServiceReference.Movie[] SearchMoviesResult;
        
        public SearchMoviesResponseBody() {
        }
        
        public SearchMoviesResponseBody(MovieServiceUser.MovieServiceReference.Movie[] SearchMoviesResult) {
            this.SearchMoviesResult = SearchMoviesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRatingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddRating", Namespace="http://tempuri.org/", Order=0)]
        public MovieServiceUser.MovieServiceReference.AddRatingRequestBody Body;
        
        public AddRatingRequest() {
        }
        
        public AddRatingRequest(MovieServiceUser.MovieServiceReference.AddRatingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRatingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string movieTitle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public float rating;
        
        public AddRatingRequestBody() {
        }
        
        public AddRatingRequestBody(string movieTitle, string user, float rating) {
            this.movieTitle = movieTitle;
            this.user = user;
            this.rating = rating;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRatingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddRatingResponse", Namespace="http://tempuri.org/", Order=0)]
        public MovieServiceUser.MovieServiceReference.AddRatingResponseBody Body;
        
        public AddRatingResponse() {
        }
        
        public AddRatingResponse(MovieServiceUser.MovieServiceReference.AddRatingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddRatingResponseBody {
        
        public AddRatingResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public MovieServiceUser.MovieServiceReference.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(MovieServiceUser.MovieServiceReference.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public MovieServiceUser.MovieServiceReference.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(MovieServiceUser.MovieServiceReference.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(bool LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUser", Namespace="http://tempuri.org/", Order=0)]
        public MovieServiceUser.MovieServiceReference.AddUserRequestBody Body;
        
        public AddUserRequest() {
        }
        
        public AddUserRequest(MovieServiceUser.MovieServiceReference.AddUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public AddUserRequestBody() {
        }
        
        public AddUserRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public MovieServiceUser.MovieServiceReference.AddUserResponseBody Body;
        
        public AddUserResponse() {
        }
        
        public AddUserResponse(MovieServiceUser.MovieServiceReference.AddUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddUserResult;
        
        public AddUserResponseBody() {
        }
        
        public AddUserResponseBody(bool AddUserResult) {
            this.AddUserResult = AddUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMovieAverageRatingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMovieAverageRating", Namespace="http://tempuri.org/", Order=0)]
        public MovieServiceUser.MovieServiceReference.GetMovieAverageRatingRequestBody Body;
        
        public GetMovieAverageRatingRequest() {
        }
        
        public GetMovieAverageRatingRequest(MovieServiceUser.MovieServiceReference.GetMovieAverageRatingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMovieAverageRatingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string movieTitle;
        
        public GetMovieAverageRatingRequestBody() {
        }
        
        public GetMovieAverageRatingRequestBody(string movieTitle) {
            this.movieTitle = movieTitle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMovieAverageRatingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMovieAverageRatingResponse", Namespace="http://tempuri.org/", Order=0)]
        public MovieServiceUser.MovieServiceReference.GetMovieAverageRatingResponseBody Body;
        
        public GetMovieAverageRatingResponse() {
        }
        
        public GetMovieAverageRatingResponse(MovieServiceUser.MovieServiceReference.GetMovieAverageRatingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMovieAverageRatingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public float GetMovieAverageRatingResult;
        
        public GetMovieAverageRatingResponseBody() {
        }
        
        public GetMovieAverageRatingResponseBody(float GetMovieAverageRatingResult) {
            this.GetMovieAverageRatingResult = GetMovieAverageRatingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetMovieAverageRatingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetMovieAverageRating", Namespace="http://tempuri.org/", Order=0)]
        public MovieServiceUser.MovieServiceReference.SetMovieAverageRatingRequestBody Body;
        
        public SetMovieAverageRatingRequest() {
        }
        
        public SetMovieAverageRatingRequest(MovieServiceUser.MovieServiceReference.SetMovieAverageRatingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetMovieAverageRatingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string movieTitle;
        
        public SetMovieAverageRatingRequestBody() {
        }
        
        public SetMovieAverageRatingRequestBody(string movieTitle) {
            this.movieTitle = movieTitle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetMovieAverageRatingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetMovieAverageRatingResponse", Namespace="http://tempuri.org/", Order=0)]
        public MovieServiceUser.MovieServiceReference.SetMovieAverageRatingResponseBody Body;
        
        public SetMovieAverageRatingResponse() {
        }
        
        public SetMovieAverageRatingResponse(MovieServiceUser.MovieServiceReference.SetMovieAverageRatingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SetMovieAverageRatingResponseBody {
        
        public SetMovieAverageRatingResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserRatingsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserRatings", Namespace="http://tempuri.org/", Order=0)]
        public MovieServiceUser.MovieServiceReference.GetUserRatingsRequestBody Body;
        
        public GetUserRatingsRequest() {
        }
        
        public GetUserRatingsRequest(MovieServiceUser.MovieServiceReference.GetUserRatingsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserRatingsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        public GetUserRatingsRequestBody() {
        }
        
        public GetUserRatingsRequestBody(string userName) {
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserRatingsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserRatingsResponse", Namespace="http://tempuri.org/", Order=0)]
        public MovieServiceUser.MovieServiceReference.GetUserRatingsResponseBody Body;
        
        public GetUserRatingsResponse() {
        }
        
        public GetUserRatingsResponse(MovieServiceUser.MovieServiceReference.GetUserRatingsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserRatingsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MovieServiceUser.MovieServiceReference.UserRating[] GetUserRatingsResult;
        
        public GetUserRatingsResponseBody() {
        }
        
        public GetUserRatingsResponseBody(MovieServiceUser.MovieServiceReference.UserRating[] GetUserRatingsResult) {
            this.GetUserRatingsResult = GetUserRatingsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MovieServiceSoapChannel : MovieServiceUser.MovieServiceReference.MovieServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MovieServiceSoapClient : System.ServiceModel.ClientBase<MovieServiceUser.MovieServiceReference.MovieServiceSoap>, MovieServiceUser.MovieServiceReference.MovieServiceSoap {
        
        public MovieServiceSoapClient() {
        }
        
        public MovieServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MovieServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovieServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovieServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MovieServiceUser.MovieServiceReference.HelloWorldResponse MovieServiceUser.MovieServiceReference.MovieServiceSoap.HelloWorld(MovieServiceUser.MovieServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            MovieServiceUser.MovieServiceReference.HelloWorldRequest inValue = new MovieServiceUser.MovieServiceReference.HelloWorldRequest();
            inValue.Body = new MovieServiceUser.MovieServiceReference.HelloWorldRequestBody();
            MovieServiceUser.MovieServiceReference.HelloWorldResponse retVal = ((MovieServiceUser.MovieServiceReference.MovieServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MovieServiceUser.MovieServiceReference.HelloWorldResponse> MovieServiceUser.MovieServiceReference.MovieServiceSoap.HelloWorldAsync(MovieServiceUser.MovieServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<MovieServiceUser.MovieServiceReference.HelloWorldResponse> HelloWorldAsync() {
            MovieServiceUser.MovieServiceReference.HelloWorldRequest inValue = new MovieServiceUser.MovieServiceReference.HelloWorldRequest();
            inValue.Body = new MovieServiceUser.MovieServiceReference.HelloWorldRequestBody();
            return ((MovieServiceUser.MovieServiceReference.MovieServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MovieServiceUser.MovieServiceReference.GetMoviesResponse MovieServiceUser.MovieServiceReference.MovieServiceSoap.GetMovies(MovieServiceUser.MovieServiceReference.GetMoviesRequest request) {
            return base.Channel.GetMovies(request);
        }
        
        public MovieServiceUser.MovieServiceReference.Movie[] GetMovies() {
            MovieServiceUser.MovieServiceReference.GetMoviesRequest inValue = new MovieServiceUser.MovieServiceReference.GetMoviesRequest();
            inValue.Body = new MovieServiceUser.MovieServiceReference.GetMoviesRequestBody();
            MovieServiceUser.MovieServiceReference.GetMoviesResponse retVal = ((MovieServiceUser.MovieServiceReference.MovieServiceSoap)(this)).GetMovies(inValue);
            return retVal.Body.GetMoviesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MovieServiceUser.MovieServiceReference.GetMoviesResponse> MovieServiceUser.MovieServiceReference.MovieServiceSoap.GetMoviesAsync(MovieServiceUser.MovieServiceReference.GetMoviesRequest request) {
            return base.Channel.GetMoviesAsync(request);
        }
        
        public System.Threading.Tasks.Task<MovieServiceUser.MovieServiceReference.GetMoviesResponse> GetMoviesAsync() {
            MovieServiceUser.MovieServiceReference.GetMoviesRequest inValue = new MovieServiceUser.MovieServiceReference.GetMoviesRequest();
            inValue.Body = new MovieServiceUser.MovieServiceReference.GetMoviesRequestBody();
            return ((MovieServiceUser.MovieServiceReference.MovieServiceSoap)(this)).GetMoviesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MovieServiceUser.MovieServiceReference.AddMovieResponse MovieServiceUser.MovieServiceReference.MovieServiceSoap.AddMovie(MovieServiceUser.MovieServiceReference.AddMovieRequest request) {
            return base.Channel.AddMovie(request);
        }
        
        public void AddMovie(string Title, string Director, int Year) {
            MovieServiceUser.MovieServiceReference.AddMovieRequest inValue = new MovieServiceUser.MovieServiceReference.AddMovieRequest();
            inValue.Body = new MovieServiceUser.MovieServiceReference.AddMovieRequestBody();
            inValue.Body.Title = Title;
            inValue.Body.Director = Director;
            inValue.Body.Year = Year;
            MovieServiceUser.MovieServiceReference.AddMovieResponse retVal = ((MovieServiceUser.MovieServiceReference.MovieServiceSoap)(this)).AddMovie(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MovieServiceUser.MovieServiceReference.AddMovieResponse> MovieServiceUser.MovieServiceReference.MovieServiceSoap.AddMovieAsync(MovieServiceUser.MovieServiceReference.AddMovieRequest request) {
            return base.Channel.AddMovieAsync(request);
        }
        
        public System.Threading.Tasks.Task<MovieServiceUser.MovieServiceReference.AddMovieResponse> AddMovieAsync(string Title, string Director, int Year) {
            MovieServiceUser.MovieServiceReference.AddMovieRequest inValue = new MovieServiceUser.MovieServiceReference.AddMovieRequest();
            inValue.Body = new MovieServiceUser.MovieServiceReference.AddMovieRequestBody();
            inValue.Body.Title = Title;
            inValue.Body.Director = Director;
            inValue.Body.Year = Year;
            return ((MovieServiceUser.MovieServiceReference.MovieServiceSoap)(this)).AddMovieAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MovieServiceUser.MovieServiceReference.SearchMoviesResponse MovieServiceUser.MovieServiceReference.MovieServiceSoap.SearchMovies(MovieServiceUser.MovieServiceReference.SearchMoviesRequest request) {
            return base.Channel.SearchMovies(request);
        }
        
        public MovieServiceUser.MovieServiceReference.Movie[] SearchMovies(string title) {
            MovieServiceUser.MovieServiceReference.SearchMoviesRequest inValue = new MovieServiceUser.MovieServiceReference.SearchMoviesRequest();
            inValue.Body = new MovieServiceUser.MovieServiceReference.SearchMoviesRequestBody();
            inValue.Body.title = title;
            MovieServiceUser.MovieServiceReference.SearchMoviesResponse retVal = ((MovieServiceUser.MovieServiceReference.MovieServiceSoap)(this)).SearchMovies(inValue);
            return retVal.Body.SearchMoviesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MovieServiceUser.MovieServiceReference.SearchMoviesResponse> MovieServiceUser.MovieServiceReference.MovieServiceSoap.SearchMoviesAsync(MovieServiceUser.MovieServiceReference.SearchMoviesRequest request) {
            return base.Channel.SearchMoviesAsync(request);
        }
        
        public System.Threading.Tasks.Task<MovieServiceUser.MovieServiceReference.SearchMoviesResponse> SearchMoviesAsync(string title) {
            MovieServiceUser.MovieServiceReference.SearchMoviesRequest inValue = new MovieServiceUser.MovieServiceReference.SearchMoviesRequest();
            inValue.Body = new MovieServiceUser.MovieServiceReference.SearchMoviesRequestBody();
            inValue.Body.title = title;
            return ((MovieServiceUser.MovieServiceReference.MovieServiceSoap)(this)).SearchMoviesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MovieServiceUser.MovieServiceReference.AddRatingResponse MovieServiceUser.MovieServiceReference.MovieServiceSoap.AddRating(MovieServiceUser.MovieServiceReference.AddRatingRequest request) {
            return base.Channel.AddRating(request);
        }
        
        public void AddRating(string movieTitle, string user, float rating) {
            MovieServiceUser.MovieServiceReference.AddRatingRequest inValue = new MovieServiceUser.MovieServiceReference.AddRatingRequest();
            inValue.Body = new MovieServiceUser.MovieServiceReference.AddRatingRequestBody();
            inValue.Body.movieTitle = movieTitle;
            inValue.Body.user = user;
            inValue.Body.rating = rating;
            MovieServiceUser.MovieServiceReference.AddRatingResponse retVal = ((MovieServiceUser.MovieServiceReference.MovieServiceSoap)(this)).AddRating(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MovieServiceUser.MovieServiceReference.AddRatingResponse> MovieServiceUser.MovieServiceReference.MovieServiceSoap.AddRatingAsync(MovieServiceUser.MovieServiceReference.AddRatingRequest request) {
            return base.Channel.AddRatingAsync(request);
        }
        
        public System.Threading.Tasks.Task<MovieServiceUser.MovieServiceReference.AddRatingResponse> AddRatingAsync(string movieTitle, string user, float rating) {
            MovieServiceUser.MovieServiceReference.AddRatingRequest inValue = new MovieServiceUser.MovieServiceReference.AddRatingRequest();
            inValue.Body = new MovieServiceUser.MovieServiceReference.AddRatingRequestBody();
            inValue.Body.movieTitle = movieTitle;
            inValue.Body.user = user;
            inValue.Body.rating = rating;
            return ((MovieServiceUser.MovieServiceReference.MovieServiceSoap)(this)).AddRatingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MovieServiceUser.MovieServiceReference.LoginResponse MovieServiceUser.MovieServiceReference.MovieServiceSoap.Login(MovieServiceUser.MovieServiceReference.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public bool Login(string username, string password) {
            MovieServiceUser.MovieServiceReference.LoginRequest inValue = new MovieServiceUser.MovieServiceReference.LoginRequest();
            inValue.Body = new MovieServiceUser.MovieServiceReference.LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            MovieServiceUser.MovieServiceReference.LoginResponse retVal = ((MovieServiceUser.MovieServiceReference.MovieServiceSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MovieServiceUser.MovieServiceReference.LoginResponse> MovieServiceUser.MovieServiceReference.MovieServiceSoap.LoginAsync(MovieServiceUser.MovieServiceReference.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<MovieServiceUser.MovieServiceReference.LoginResponse> LoginAsync(string username, string password) {
            MovieServiceUser.MovieServiceReference.LoginRequest inValue = new MovieServiceUser.MovieServiceReference.LoginRequest();
            inValue.Body = new MovieServiceUser.MovieServiceReference.LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((MovieServiceUser.MovieServiceReference.MovieServiceSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MovieServiceUser.MovieServiceReference.AddUserResponse MovieServiceUser.MovieServiceReference.MovieServiceSoap.AddUser(MovieServiceUser.MovieServiceReference.AddUserRequest request) {
            return base.Channel.AddUser(request);
        }
        
        public bool AddUser(string username, string password) {
            MovieServiceUser.MovieServiceReference.AddUserRequest inValue = new MovieServiceUser.MovieServiceReference.AddUserRequest();
            inValue.Body = new MovieServiceUser.MovieServiceReference.AddUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            MovieServiceUser.MovieServiceReference.AddUserResponse retVal = ((MovieServiceUser.MovieServiceReference.MovieServiceSoap)(this)).AddUser(inValue);
            return retVal.Body.AddUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MovieServiceUser.MovieServiceReference.AddUserResponse> MovieServiceUser.MovieServiceReference.MovieServiceSoap.AddUserAsync(MovieServiceUser.MovieServiceReference.AddUserRequest request) {
            return base.Channel.AddUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<MovieServiceUser.MovieServiceReference.AddUserResponse> AddUserAsync(string username, string password) {
            MovieServiceUser.MovieServiceReference.AddUserRequest inValue = new MovieServiceUser.MovieServiceReference.AddUserRequest();
            inValue.Body = new MovieServiceUser.MovieServiceReference.AddUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((MovieServiceUser.MovieServiceReference.MovieServiceSoap)(this)).AddUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MovieServiceUser.MovieServiceReference.GetMovieAverageRatingResponse MovieServiceUser.MovieServiceReference.MovieServiceSoap.GetMovieAverageRating(MovieServiceUser.MovieServiceReference.GetMovieAverageRatingRequest request) {
            return base.Channel.GetMovieAverageRating(request);
        }
        
        public float GetMovieAverageRating(string movieTitle) {
            MovieServiceUser.MovieServiceReference.GetMovieAverageRatingRequest inValue = new MovieServiceUser.MovieServiceReference.GetMovieAverageRatingRequest();
            inValue.Body = new MovieServiceUser.MovieServiceReference.GetMovieAverageRatingRequestBody();
            inValue.Body.movieTitle = movieTitle;
            MovieServiceUser.MovieServiceReference.GetMovieAverageRatingResponse retVal = ((MovieServiceUser.MovieServiceReference.MovieServiceSoap)(this)).GetMovieAverageRating(inValue);
            return retVal.Body.GetMovieAverageRatingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MovieServiceUser.MovieServiceReference.GetMovieAverageRatingResponse> MovieServiceUser.MovieServiceReference.MovieServiceSoap.GetMovieAverageRatingAsync(MovieServiceUser.MovieServiceReference.GetMovieAverageRatingRequest request) {
            return base.Channel.GetMovieAverageRatingAsync(request);
        }
        
        public System.Threading.Tasks.Task<MovieServiceUser.MovieServiceReference.GetMovieAverageRatingResponse> GetMovieAverageRatingAsync(string movieTitle) {
            MovieServiceUser.MovieServiceReference.GetMovieAverageRatingRequest inValue = new MovieServiceUser.MovieServiceReference.GetMovieAverageRatingRequest();
            inValue.Body = new MovieServiceUser.MovieServiceReference.GetMovieAverageRatingRequestBody();
            inValue.Body.movieTitle = movieTitle;
            return ((MovieServiceUser.MovieServiceReference.MovieServiceSoap)(this)).GetMovieAverageRatingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MovieServiceUser.MovieServiceReference.SetMovieAverageRatingResponse MovieServiceUser.MovieServiceReference.MovieServiceSoap.SetMovieAverageRating(MovieServiceUser.MovieServiceReference.SetMovieAverageRatingRequest request) {
            return base.Channel.SetMovieAverageRating(request);
        }
        
        public void SetMovieAverageRating(string movieTitle) {
            MovieServiceUser.MovieServiceReference.SetMovieAverageRatingRequest inValue = new MovieServiceUser.MovieServiceReference.SetMovieAverageRatingRequest();
            inValue.Body = new MovieServiceUser.MovieServiceReference.SetMovieAverageRatingRequestBody();
            inValue.Body.movieTitle = movieTitle;
            MovieServiceUser.MovieServiceReference.SetMovieAverageRatingResponse retVal = ((MovieServiceUser.MovieServiceReference.MovieServiceSoap)(this)).SetMovieAverageRating(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MovieServiceUser.MovieServiceReference.SetMovieAverageRatingResponse> MovieServiceUser.MovieServiceReference.MovieServiceSoap.SetMovieAverageRatingAsync(MovieServiceUser.MovieServiceReference.SetMovieAverageRatingRequest request) {
            return base.Channel.SetMovieAverageRatingAsync(request);
        }
        
        public System.Threading.Tasks.Task<MovieServiceUser.MovieServiceReference.SetMovieAverageRatingResponse> SetMovieAverageRatingAsync(string movieTitle) {
            MovieServiceUser.MovieServiceReference.SetMovieAverageRatingRequest inValue = new MovieServiceUser.MovieServiceReference.SetMovieAverageRatingRequest();
            inValue.Body = new MovieServiceUser.MovieServiceReference.SetMovieAverageRatingRequestBody();
            inValue.Body.movieTitle = movieTitle;
            return ((MovieServiceUser.MovieServiceReference.MovieServiceSoap)(this)).SetMovieAverageRatingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MovieServiceUser.MovieServiceReference.GetUserRatingsResponse MovieServiceUser.MovieServiceReference.MovieServiceSoap.GetUserRatings(MovieServiceUser.MovieServiceReference.GetUserRatingsRequest request) {
            return base.Channel.GetUserRatings(request);
        }
        
        public MovieServiceUser.MovieServiceReference.UserRating[] GetUserRatings(string userName) {
            MovieServiceUser.MovieServiceReference.GetUserRatingsRequest inValue = new MovieServiceUser.MovieServiceReference.GetUserRatingsRequest();
            inValue.Body = new MovieServiceUser.MovieServiceReference.GetUserRatingsRequestBody();
            inValue.Body.userName = userName;
            MovieServiceUser.MovieServiceReference.GetUserRatingsResponse retVal = ((MovieServiceUser.MovieServiceReference.MovieServiceSoap)(this)).GetUserRatings(inValue);
            return retVal.Body.GetUserRatingsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MovieServiceUser.MovieServiceReference.GetUserRatingsResponse> MovieServiceUser.MovieServiceReference.MovieServiceSoap.GetUserRatingsAsync(MovieServiceUser.MovieServiceReference.GetUserRatingsRequest request) {
            return base.Channel.GetUserRatingsAsync(request);
        }
        
        public System.Threading.Tasks.Task<MovieServiceUser.MovieServiceReference.GetUserRatingsResponse> GetUserRatingsAsync(string userName) {
            MovieServiceUser.MovieServiceReference.GetUserRatingsRequest inValue = new MovieServiceUser.MovieServiceReference.GetUserRatingsRequest();
            inValue.Body = new MovieServiceUser.MovieServiceReference.GetUserRatingsRequestBody();
            inValue.Body.userName = userName;
            return ((MovieServiceUser.MovieServiceReference.MovieServiceSoap)(this)).GetUserRatingsAsync(inValue);
        }
    }
}
